---
title: "Fisher's Exact P-Values"
author: Andrew Marder
draft: true
---

The first thing I want to do is define a function that makes it easy to permute students within seats.

```{r}
one_draw <- function(students, rows) {
    # Make sure inputs are numeric values only.
    stopifnot(is.numeric(students))
    stopifnot(is.numeric(rows))

    # Make sure the total number of students equals the total number
    # of seats.
    stopifnot(length(students) == sum(rows))

    # Randomly assign students to seats.
    shuffled <- sample(students)

    # Figure out which row every student is sitting in.
    row_number <- unlist(
        lapply(1:length(rows), function(i) rep(i, rows[i]))
    )

    # Set up a data frame to hold this permutation.
    x <- data.frame(
        student = shuffled,
        row = row_number
    )

    # Mark where a student is sitting above a friend.
    x$above_friend <- (x$student == c(x$student[2:nrow(x)], NA)) &
        (x$row == c(x$row[2:nrow(x)], NA))
    x$above_friend[nrow(x)] <- FALSE

    # Mark where a student is sitting below a friend.
    x$below_friend <- (x$student == c(NA, x$student[1:(nrow(x)-1)])) &
        (x$row == c(NA, x$row[1:(nrow(x)-1)]))
    x$below_friend[1] <- FALSE

    # Mark where a student is sitting next to a friend.
    x$next_to_friend <- x$above_friend | x$below_friend

    # Return this permutation.
    return(x)
}

# Let's look at what a permutation looks like.
one_draw(
    students = c(1, 1, 1, 1, 2, 2, 2, 2),
    rows = c(4, 4)
)
```

Given 90 students, 10 sections, and 9 rows of equal length, what proportion of students sit next to friends? Let's run 1000 simulations to find out.

```{r}
n <- 1000
students <- rep(1:10, 9)
rows <- rep(10, 9)

simulations <- data.frame(
    number = 1:n,
    proportion_sitting_next_to_a_friend = sapply(1:n, function(i) {
        x <- one_draw(students = students, rows = rows)
        return(mean(x$next_to_friend))
    })
)

# Plot the distribution.
library(ggplot2)

ggplot(simulations, aes(x = proportion_sitting_next_to_a_friend)) + geom_density() + xlim(0, 1)
```

How unlikely is it to see 25% of students sitting next to a friend? Calculate the p-value.

```{r}
mean(simulations$proportion_sitting_next_to_a_friend >= 0.25)
```
